#pragma once
#include "MeshRendererComponent.h"
#include "TransformComponent.h"
#include "InputManagerComponent.h"
#include "ColliderComponent.h"
#include "SkinnedMeshRendererComponent.h"
#include "AnimatorComponent.h"
#include "HumanoidControllerComponent.h"
#include "WeaponControllerComponent.h"
#include "RigidbodyComponent.h"
#include "CameraComponent.h"
#include "EffectComponent.h"
#include "ParticleEmitterComponent.h"
#include "ParticleComponent.h"
#include "TargetBoardControllerComponent.h"

#include "Character.h"
#include "Object.h"